// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

void* winrt_make_App2_Calculator_pg()
{
    return winrt::detach_abi(winrt::make<winrt::App2::factory_implementation::Calculator_pg>());
}
WINRT_EXPORT namespace winrt::App2
{
    Calculator_pg::Calculator_pg() :
        Calculator_pg(make<App2::implementation::Calculator_pg>())
    {
    }
}
