// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

void* winrt_make_App2_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::App2::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::App2
{
    MainWindow::MainWindow() :
        MainWindow(make<App2::implementation::MainWindow>())
    {
    }
}
