// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

void* winrt_make_App2_Resuit()
{
    return winrt::detach_abi(winrt::make<winrt::App2::factory_implementation::Resuit>());
}
WINRT_EXPORT namespace winrt::App2
{
    Resuit::Resuit() :
        Resuit(make<App2::implementation::Resuit>())
    {
    }
}
