
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif


namespace winrt::App2::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct SettingT : public ::winrt::App2::implementation::Setting_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename SettingT::base_type;
        using base_type::base_type;
        using class_type = typename SettingT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox SavePath()
        {
            return _SavePath;
        }
        void SavePath(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _SavePath = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch IsAutoSave()
        {
            return _IsAutoSave;
        }
        void IsAutoSave(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _IsAutoSave = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox ResultPrecision()
        {
            return _ResultPrecision;
        }
        void ResultPrecision(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _ResultPrecision = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox culselect()
        {
            return _culselect;
        }
        void culselect(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _culselect = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch IsShowWelcome()
        {
            return _IsShowWelcome;
        }
        void IsShowWelcome(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _IsShowWelcome = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct Setting_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _SavePath{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _IsAutoSave{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _ResultPrecision{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _culselect{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _IsShowWelcome{nullptr};
    };
}

