// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_App2_H
#define WINRT_App2_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.250303.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.250303.1"
#include "winrt/impl/Microsoft.UI.Composition.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Controls.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.2.h"
#include "winrt/impl/App2.2.h"
namespace winrt::impl
{
    template <typename D> auto consume_App2_ICalculator_pg<D>::MyProperty() const
    {
        int32_t value{};
        if constexpr (!std::is_same_v<D, winrt::App2::ICalculator_pg>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::App2::ICalculator_pg, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::App2::ICalculator_pg>**)&_winrt_casted_result;
            check_hresult(_winrt_abi_type->get_MyProperty(&value));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::App2::ICalculator_pg>**)this;
            check_hresult(_winrt_abi_type->get_MyProperty(&value));
        }
        return value;
    }
    template <typename D> auto consume_App2_ICalculator_pg<D>::MyProperty(int32_t value) const
    {
        if constexpr (!std::is_same_v<D, winrt::App2::ICalculator_pg>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::App2::ICalculator_pg, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::App2::ICalculator_pg>**)&_winrt_casted_result;
            check_hresult(_winrt_abi_type->put_MyProperty(value));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::App2::ICalculator_pg>**)this;
            check_hresult(_winrt_abi_type->put_MyProperty(value));
        }
    }
    template <typename D> auto consume_App2_IHome<D>::MyProperty() const
    {
        int32_t value{};
        if constexpr (!std::is_same_v<D, winrt::App2::IHome>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::App2::IHome, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::App2::IHome>**)&_winrt_casted_result;
            check_hresult(_winrt_abi_type->get_MyProperty(&value));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::App2::IHome>**)this;
            check_hresult(_winrt_abi_type->get_MyProperty(&value));
        }
        return value;
    }
    template <typename D> auto consume_App2_IHome<D>::MyProperty(int32_t value) const
    {
        if constexpr (!std::is_same_v<D, winrt::App2::IHome>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::App2::IHome, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::App2::IHome>**)&_winrt_casted_result;
            check_hresult(_winrt_abi_type->put_MyProperty(value));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::App2::IHome>**)this;
            check_hresult(_winrt_abi_type->put_MyProperty(value));
        }
    }
    template <typename D> auto consume_App2_IMainWindow<D>::MyProperty() const
    {
        int32_t value{};
        if constexpr (!std::is_same_v<D, winrt::App2::IMainWindow>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::App2::IMainWindow, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::App2::IMainWindow>**)&_winrt_casted_result;
            check_hresult(_winrt_abi_type->get_MyProperty(&value));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::App2::IMainWindow>**)this;
            check_hresult(_winrt_abi_type->get_MyProperty(&value));
        }
        return value;
    }
    template <typename D> auto consume_App2_IMainWindow<D>::MyProperty(int32_t value) const
    {
        if constexpr (!std::is_same_v<D, winrt::App2::IMainWindow>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::App2::IMainWindow, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::App2::IMainWindow>**)&_winrt_casted_result;
            check_hresult(_winrt_abi_type->put_MyProperty(value));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::App2::IMainWindow>**)this;
            check_hresult(_winrt_abi_type->put_MyProperty(value));
        }
    }
    template <typename D> auto consume_App2_IResuit<D>::MyProperty() const
    {
        int32_t value{};
        if constexpr (!std::is_same_v<D, winrt::App2::IResuit>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::App2::IResuit, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::App2::IResuit>**)&_winrt_casted_result;
            check_hresult(_winrt_abi_type->get_MyProperty(&value));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::App2::IResuit>**)this;
            check_hresult(_winrt_abi_type->get_MyProperty(&value));
        }
        return value;
    }
    template <typename D> auto consume_App2_IResuit<D>::MyProperty(int32_t value) const
    {
        if constexpr (!std::is_same_v<D, winrt::App2::IResuit>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::App2::IResuit, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::App2::IResuit>**)&_winrt_casted_result;
            check_hresult(_winrt_abi_type->put_MyProperty(value));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::App2::IResuit>**)this;
            check_hresult(_winrt_abi_type->put_MyProperty(value));
        }
    }
    template <typename D> auto consume_App2_ISetting<D>::MyProperty() const
    {
        int32_t value{};
        if constexpr (!std::is_same_v<D, winrt::App2::ISetting>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::App2::ISetting, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::App2::ISetting>**)&_winrt_casted_result;
            check_hresult(_winrt_abi_type->get_MyProperty(&value));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::App2::ISetting>**)this;
            check_hresult(_winrt_abi_type->get_MyProperty(&value));
        }
        return value;
    }
    template <typename D> auto consume_App2_ISetting<D>::MyProperty(int32_t value) const
    {
        if constexpr (!std::is_same_v<D, winrt::App2::ISetting>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::App2::ISetting, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::App2::ISetting>**)&_winrt_casted_result;
            check_hresult(_winrt_abi_type->put_MyProperty(value));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::App2::ISetting>**)this;
            check_hresult(_winrt_abi_type->put_MyProperty(value));
        }
    }
    template <typename D>
    struct produce<D, winrt::App2::ICalculator_pg> : produce_base<D, winrt::App2::ICalculator_pg>
    {
        int32_t __stdcall get_MyProperty(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_MyProperty(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::App2::IHome> : produce_base<D, winrt::App2::IHome>
    {
        int32_t __stdcall get_MyProperty(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_MyProperty(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::App2::IMainWindow> : produce_base<D, winrt::App2::IMainWindow>
    {
        int32_t __stdcall get_MyProperty(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_MyProperty(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::App2::IResuit> : produce_base<D, winrt::App2::IResuit>
    {
        int32_t __stdcall get_MyProperty(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_MyProperty(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::App2::ISetting> : produce_base<D, winrt::App2::ISetting>
    {
        int32_t __stdcall get_MyProperty(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_MyProperty(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::App2
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::App2::ICalculator_pg> : winrt::impl::hash_base {};
    template<> struct hash<winrt::App2::IHome> : winrt::impl::hash_base {};
    template<> struct hash<winrt::App2::IMainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::App2::IResuit> : winrt::impl::hash_base {};
    template<> struct hash<winrt::App2::ISetting> : winrt::impl::hash_base {};
    template<> struct hash<winrt::App2::Calculator_pg> : winrt::impl::hash_base {};
    template<> struct hash<winrt::App2::Home> : winrt::impl::hash_base {};
    template<> struct hash<winrt::App2::MainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::App2::Resuit> : winrt::impl::hash_base {};
    template<> struct hash<winrt::App2::Setting> : winrt::impl::hash_base {};
    template<> struct hash<winrt::App2::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
