namespace App2
{
    [default_interface]
    runtimeclass Setting : Microsoft.UI.Xaml.Controls.Page
    {
        Setting();
        Int32 MyProperty;
        Microsoft.UI.Xaml.Controls.ToggleSwitch IsShowWelcome{ get; };
    }
}
